package com.shouxin.qa.field;
import jakarta.validation.Valid;import jakarta.validation.constraints.NotBlank;import org.springframework.jdbc.core.JdbcTemplate;import org.springframework.security.access.prepost.PreAuthorize;import org.springframework.transaction.annotation.Transactional;import org.springframework.web.bind.annotation.*;import java.util.*;
@RestController @RequestMapping("/api/admin/field-schemes") @PreAuthorize("hasAnyRole('QA_ADMIN','SYS_ADMIN')")
public class FieldSchemeAdminController{private final JdbcTemplate jdbc;public FieldSchemeAdminController(JdbcTemplate j){jdbc=j;}
 @PostMapping @Transactional public Map<String,Object> create(@Valid @RequestBody Req r){String id=UUID.randomUUID().toString();jdbc.update("INSERT INTO qa_field_scheme(id,scheme_code,scheme_name,description,is_default,enabled) VALUES(?,?,?,?,0,1)",id,r.code(),r.name(),r.description());return jdbc.queryForMap("SELECT id,scheme_code,scheme_name,description,is_default,enabled FROM qa_field_scheme WHERE id=?",id);}
 @PostMapping("/{id}/fields") @Transactional public Map<String,Object> addField(@PathVariable String id,@Valid @RequestBody FieldReq r){String fid=UUID.randomUUID().toString();jdbc.update("INSERT INTO qa_field_config(id,scheme_id,field_code,field_name,field_type,required,list_visible,searchable,sort_order,options_json) VALUES(?,?,?,?,?,?,?,?,?,?)",fid,id,r.code(),r.name(),r.type(),r.required()?1:0,r.listVisible()?1:0,r.searchable()?1:0,r.sortOrder(),r.optionsJson());return jdbc.queryForMap("SELECT id,field_code,field_name,field_type,required,list_visible,searchable,sort_order,options_json FROM qa_field_config WHERE id=?",fid);}
 @PutMapping("/{id}") @Transactional public void update(@PathVariable String id,@Valid @RequestBody Req r){if(jdbc.update("UPDATE qa_field_scheme SET scheme_name=?,description=?,updated_at=CURRENT_TIMESTAMP WHERE id=? AND enabled=1",r.name(),r.description(),id)!=1)throw new NoSuchElementException("字段方案不存在");}
 @PutMapping("/{id}/fields/{fieldId}") @Transactional public void updateField(@PathVariable String id,@PathVariable String fieldId,@Valid @RequestBody FieldReq r){if(jdbc.update("UPDATE qa_field_config SET field_name=?,field_type=?,required=?,list_visible=?,searchable=?,sort_order=?,options_json=?,updated_at=CURRENT_TIMESTAMP WHERE id=? AND scheme_id=?",r.name(),r.type(),r.required()?1:0,r.listVisible()?1:0,r.searchable()?1:0,r.sortOrder(),r.optionsJson(),fieldId,id)!=1)throw new NoSuchElementException("字段不存在");}
 @DeleteMapping("/{id}/fields/{fieldId}") @Transactional public void deleteField(@PathVariable String id,@PathVariable String fieldId){if(jdbc.update("DELETE FROM qa_field_config WHERE id=? AND scheme_id=?",fieldId,id)!=1)throw new NoSuchElementException("字段不存在");}
 @DeleteMapping("/{id}") @Transactional public void delete(@PathVariable String id){if(jdbc.update("UPDATE qa_field_scheme SET enabled=0,updated_at=CURRENT_TIMESTAMP WHERE id=? AND is_default=0",id)!=1)throw new IllegalArgumentException("默认方案不可删除或方案不存在");}
 public record Req(@NotBlank String code,@NotBlank String name,String description){} public record FieldReq(@NotBlank String code,@NotBlank String name,@NotBlank String type,boolean required,boolean listVisible,boolean searchable,int sortOrder,String optionsJson){}
}
